version: '3'
services:
  telegraf:
    build:
      context: ./telegraf
      dockerfile: ./Dockerfile
    image: frbsc/monitoring:telegraf
    # environment:
    #   HOSTNAME: "${uname -n}"
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped